### ISSUE TITLE
Support for confidence level of image? Do we have any system to add confidence level of image before searching image on screen

### ISSUE THREAD

**Issue by SUDARSHANCHAUDHARI** [AirtestProject/AirtestIDE#191]
Hello All,

Do we have any support to manipulate the confidence level of the image?
Sometimes the image is in the background (behind the popup advertisement window and AirTest IDE still able to identify it).

Is there any way to add confidence level in the code so that IDE can perform an action(wait, touch, exists) only if image passes the certain percentage of confidence level.

Is there any way to add confidence level in the following the code : 
wait(Template(r"image_name.png", threshold=0.8, target_pos=5, rgb=False, record_pos=(-0.392, 0.531), resolution=(1440, 2560)))

**Comment by rockywhisper** [comment]
@SUDARSHANCHAUDHARI   Hi, double-click on the image in your script,  you can set the threshold of the image recognition.  This threshold only works for the image you clicked.

If you want to set all the recognition threshold of the whole script, you can add lines below in your script:
```python
from airtest.core.settings import Settings as ST
ST.THRESHOLD = 0.7  # default is 0.6, quite low
```

**Comment by SUDARSHANCHAUDHARI** [comment]
Yes, that I know.
but is the threshold and confidence level are two different things.
As sometimes IDE able to recognize image even if it is behind the pop-up advertisement window.
how can I avoid this?

**Comment by rockywhisper** [comment]
@SUDARSHANCHAUDHARI  Hi
1. When the IDE exec the code-line that contains a picture, the recognition algorithm will try to find a similar area in device current screenshot. It will find a result (the most similar area in the device screen), and a confidence which means the similarity of the image in code-line and the result area.

When the confidence of the result is minor than the THRESHOLD we set in airtest.core.settings, the result will be abandoned. IDE will throw out a TargetNotFoundError.

2. If you found IDE recognize a wrong result, you can check the HTML-report first, see the confidence of the wrong step. Like this example:

When I set the threshold of this image to 0.55:
![image](https://user-images.githubusercontent.com/8188879/43060758-d7b02df2-8e84-11e8-9b0c-96aaff74eede.png)
the result is wrong:
![image](https://user-images.githubusercontent.com/8188879/43060746-c4709c4a-8e84-11e8-95a1-c9da51143955.png)

If I want to filter this wrong result, I can adjust the threshold to a higher level like 0.70, now IDE won't find the wrong answer, but stop the script running because of a TargetNotFoundError:
![image](https://user-images.githubusercontent.com/8188879/43060886-6d1695f2-8e85-11e8-88f9-9635125833e6.png)

**Comment by SUDARSHANCHAUDHARI** [comment]
Thank you for this detailed explanation, Now I fully understand.
I really appreciate it!!
You can close this issue
